name: Automated tests

on:                                           # условия запуска тестов на гитхабе
  push

jobs:                                         # задания (алгоритм запуска тестов)
    tests:                                    # название джобы
      runs-on: ubuntu-latest                  # на какой ОС запускать тесты

      steps:
        - name: Checkout repository           # название шага
          uses: actions/checkout@v3           # название спец. заготовленного action-а
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python version: "3.10"
        - name: Install Chrome
          run: sudo apt-get install google-chrome-stable
        - name: Install dependensies
          run: pip install -r requirements.txt
        - name: Run tests
          run: pytest -v --tb=line --language=es
